project:
  type: website

website:
  title: ""
  favicon: "./files/favicon.ico"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: research.qmd
        text: Research
      - href: resume.qmd
        text: Resume
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/mqsirera/
      - icon: github
        href: https://github.com/mqsirera

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



