---
title: My Research
layout: page
---

Hello and a warm welcome to my research corner! This is the place where I share my latest research papers and articles. It's all about digging into the fascinating world of AI and all its different applications. Join me in this scholarly adventure as we explore exciting ideas, challenge the norm, and have some intellectual fun along the way. Feel free to dive into my research, and let's keep the conversation going!

## Articles

| Title        | Authors             | Venue        | Download PDF |
| ------------ | ------------------- | ------------ | ------------ |
| Neural Point Processes for Pixel-wise Regression | Chengzhi Shi, Gözde Özcan, **Miquel Sirera Perelló**, Stratis Ioannidis | AISTATS 2025 | [Download](./research/NPP.pdf "Download paper") |
| JARVIS: Disjoint Large Language Models on Radio VLANs for Intelligent Services | **Miquel Sirera Perelló**, Joshua Groen, Wan Liu, Stratis Ioannidis, Kaushik Chowdhury | IEEE MILCOM 2024 | [Download](./research/JARVIS.pdf "Download paper") |
| T-PRIME: Transformer-based Protocol Identification for Machine-learning at the Edge | Mauro Belgiovine, Joshua Groen, **Miquel Sirera Perelló**, Chinenye Tassie, Sage Trudeau, Stratis Ioannidis, Kaushik Chowdhury | IEEE INFOCOM 2024 | [Download](./research/T-PRIME.pdf "Download paper") |
| MEGATRON: Machine Learning in 5G with Analysis of Traffic in Open Radio Access Networks |	Mauro Belgiovine, Jerry Gu, Joshua Groen, **Miquel Sirera Perelló**, Utku Demir, Kaushik Chowdhury | ICNC 2024 | [Download](./research/MEGATRON.pdf "Download paper") |
| Deep Learning for Wireless Communications | **Miquel Sirera Perelló**, Kaushik Chowdhury, Albert Cabellos-Aparicio | Bachelor Thesis 2023 | [Download](./research/TFG.pdf "Download paper") |

## Attended Conferences

- **MILCOM 2024** — Washington DC *(presented)*  
  [Download Poster](./reasearch/Poster_JARVIS.pdf){.btn .btn-primary}

- **ICLR 2024** — Singapore *(attended)*

- **AISTATS 2025** — Phuket *(presented)*  
  [Download Poster](./research/Poster_NPP.pdf){.btn .btn-primary}
