---
title: Resume
layout: page
---


[Download My Academic CV - PDF](./files/MiquelSirera_AcademicCV_Dec2024.pdf "Miquel Sirera's Academic CV"){.btn .btn-primary}
[Download My Regular CV - PDF](./files/MiquelSireraPerelloPhDNEU_Dec2024.pdf "Miquel Sirera's CV"){.btn .btn-primary}

::: panel-tabset
# Profile

::: {style="text-align:justify"}
I am a motivated graduate with a bachelor's degree in Data Science and Engineering from Universitat Politècnica de Catalunya. My academic journey has equipped me with a strong foundation in computer science, mathematics, statistics, and signal processing. Having recently completed my degree, I am now driven by a profound aspiration to further my knowledge and make significant contributions to the field of Computer Engineering through the pursuit of a Ph.D. I am enthusiastic about engaging in cutting-edge research, pushing the boundaries of technological innovation, and making a meaningful impact. With a proactive work ethic and a dedication to academic excellence, I am excited to embark on an advanced academic path and play a role in shaping the future of computer engineering.
:::

# Education {style="text-align:justify"}

### PhD in Computer Engineering, Norhteastern University, Boston {style="text-align:justify"}

*January 2024 - Present*

As a Ph.D. student in Computer Engineering at Northeastern University, my research focuses on the intersection of Machine Learning, Large Language Models (LLMs), Distributed Training and Inference, and Wireless Communications. I am deeply interested in both advancing core AI methodologies and exploring how telecommunications can be optimized to support AI systems, such as through efficient distributed inference and scalable deployments. At the same time, I investigate how AI can transform telecommunications by improving network performance, automating resource management, and enhancing security. By bridging these domains, I aim to contribute to innovations that will shape the future of both AI and wireless communications, driving advancements in next-generation technologies like 6G and beyond.

### BSc degree in Data Science and Engineering, Universitat Politècnica de Catalunya, Barcelona {style="text-align:justify"}

*September 2019 - July 2023*

Recently graduated with a strong academic record, I proudly achieved an exceptional GPA of 8.89 out of 10 in my bachelor's education, demonstrating my unwavering commitment to academic excellence. Particularly noteworthy, I earned honorific distinctions in four rigorous courses: Discrete Mathematics and Logic, Mathematical Optimization, Search and Analysis of Information, and Advanced Topics of Data Science.

### High School, La Salle Bonanova, Barcelona {style="text-align:justify"}

*September 2017 - June 2019*

I graduated with honors, achieving a remarkable score of 13.556 out of 14 in the university entrance exams (PAU). This accomplishment earned me the prestigious PAU distinction. Additionally, I actively participated in various math contests, including Pangea and "Fem Matemàtiques", further underscoring my commitment to academic excellence. My enthusiasm for mathematics led me to engage in advanced enrichment math classes, which significantly enriched my mathematical insights and skills.

# Experience {style="text-align:justify"}

### Genesys Lab at Northeastern University, BSc thesis development {style="text-align:justify"}

*February 2023 - July 2023*

While developing my Bachelor's thesis, I worked alongside a research team at the university focused on integrating Artificial Intelligence into wireless communications. This group is part of the Institute for the Wireless Internet of Things, and their primary goal is to create advanced solutions for wireless communication challenges. In this context, I was responsible for devising and implementing AI-driven approaches, specifically in the realm of signal classification. This experience solidified my understanding of AI's impact on wireless technologies and fueled my enthusiasm for contributing further to this evolving field.

### Abi Global Health, AI Engineer internship {style="text-align:justify"}

*March 2022 - December 2022*

I completed an internship at a prominent global tele-health company, where I played a pivotal role in advancing monitoring capabilities within the MLOps framework. In addition, I provided valuable support to the AI Lab by contributing to the creation of novel machine learning models and enhancing pre-existing solutions.

# Personal projects {style="text-align:justify"}

### Datathon/Hackathon participation {style="text-align:justify"}

*2021 - Present*

Alongside my coursework, I actively honed my practical skills by participating in esteemed programming competitions, including both the UPC Datathon and the Google Hash Code in two separate occasions. These experiences, supported by sponsorship from major tech industry players, have fortified my problem-solving prowess, teamwork skills and underscored my dedication to pushing the boundaries of knowledge and innovation. I really enjoy participating in this kind of events and I look forward to do it more in the near future.

### BECO, a tool to boost environmentally conscious decisions {style="text-align:justify"}

*February 2022 - June 2022*

I successfully executed the development of a software solution for Naptilus Tech Lab, addressing a complex challenge centered around leveraging extensive user data to mitigate individual carbon footprints. The outcome of our efforts materialized as "BECO", an innovative application service meticulously crafted using advanced machine learning techniques. This platform adeptly guided users by suggesting environmentally conscious establishments, underscoring our commitment to fostering sustainable choices.

# Skills {style="text-align:justify"}
::: {style="text-align:justify"}
I bring a diverse skill set and a deep passion for what I do. My foundation lies in critical thinking and problem-solving, allowing me to tackle complex challenges with ease. Collaboration is at the core of my approach, as my ability to work seamlessly within a team environment fosters creativity and innovation. Being a fast learner is not just a skill, but a mindset that fuels my continuous growth and exploration of new domains. Adaptability is second nature to me; I thrive in dynamic environments, readily embracing change. My unwavering commitment to excellence is the driving force behind my endeavors, and I couple it with effective time management to ensure tasks are not only completed but mastered. With a keen eye for detail and a methodical approach, I maintain a high level of organization in all aspects of my work. Together, these skills form the foundation of my approach to achieving success.
:::
:::